apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bcm-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: bcm-agent
  app.kubernetes.io/managed-by: kustomize
